# fly.toml app configuration file generated for ballistic-calculator-nameless-lake-2284 on 2024-03-23T21:25:55-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ballistic-calculator-nameless-lake-2284'
primary_region = 'lax'

[build]
  builder = 'paketobuildpacks/builder:base'
  buildpacks = ['gcr.io/paketo-buildpacks/go']

[env]
  PORT = '8080'

[[services]]
  protocol = 'tcp'
  internal_port = 8080

[[services.ports]]
    port = 443
    handlers = ['tls']

    [services.ports.tls_options]

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
