// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: pb/rifle.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRifleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rifle *Rifle `protobuf:"bytes,1,opt,name=rifle,proto3" json:"rifle,omitempty"`
}

func (x *CreateRifleRequest) Reset() {
	*x = CreateRifleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_rifle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRifleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRifleRequest) ProtoMessage() {}

func (x *CreateRifleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rifle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRifleRequest.ProtoReflect.Descriptor instead.
func (*CreateRifleRequest) Descriptor() ([]byte, []int) {
	return file_pb_rifle_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRifleRequest) GetRifle() *Rifle {
	if x != nil {
		return x.Rifle
	}
	return nil
}

type CreateRifleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rifle *Rifle `protobuf:"bytes,1,opt,name=rifle,proto3" json:"rifle,omitempty"`
}

func (x *CreateRifleResponse) Reset() {
	*x = CreateRifleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_rifle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRifleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRifleResponse) ProtoMessage() {}

func (x *CreateRifleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rifle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRifleResponse.ProtoReflect.Descriptor instead.
func (*CreateRifleResponse) Descriptor() ([]byte, []int) {
	return file_pb_rifle_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRifleResponse) GetRifle() *Rifle {
	if x != nil {
		return x.Rifle
	}
	return nil
}

type ListRiflesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListRiflesRequest) Reset() {
	*x = ListRiflesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_rifle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRiflesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRiflesRequest) ProtoMessage() {}

func (x *ListRiflesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rifle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRiflesRequest.ProtoReflect.Descriptor instead.
func (*ListRiflesRequest) Descriptor() ([]byte, []int) {
	return file_pb_rifle_proto_rawDescGZIP(), []int{2}
}

type ListRiflesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rifles []*Rifle `protobuf:"bytes,1,rep,name=rifles,proto3" json:"rifles,omitempty"`
}

func (x *ListRiflesResponse) Reset() {
	*x = ListRiflesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_rifle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRiflesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRiflesResponse) ProtoMessage() {}

func (x *ListRiflesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rifle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRiflesResponse.ProtoReflect.Descriptor instead.
func (*ListRiflesResponse) Descriptor() ([]byte, []int) {
	return file_pb_rifle_proto_rawDescGZIP(), []int{3}
}

func (x *ListRiflesResponse) GetRifles() []*Rifle {
	if x != nil {
		return x.Rifles
	}
	return nil
}

type GetRifleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RifleId int64 `protobuf:"varint,1,opt,name=rifle_id,json=rifleId,proto3" json:"rifle_id,omitempty"`
}

func (x *GetRifleRequest) Reset() {
	*x = GetRifleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_rifle_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRifleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRifleRequest) ProtoMessage() {}

func (x *GetRifleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rifle_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRifleRequest.ProtoReflect.Descriptor instead.
func (*GetRifleRequest) Descriptor() ([]byte, []int) {
	return file_pb_rifle_proto_rawDescGZIP(), []int{4}
}

func (x *GetRifleRequest) GetRifleId() int64 {
	if x != nil {
		return x.RifleId
	}
	return 0
}

type GetRifleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rifle *Rifle `protobuf:"bytes,1,opt,name=rifle,proto3" json:"rifle,omitempty"`
}

func (x *GetRifleResponse) Reset() {
	*x = GetRifleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_rifle_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRifleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRifleResponse) ProtoMessage() {}

func (x *GetRifleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rifle_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRifleResponse.ProtoReflect.Descriptor instead.
func (*GetRifleResponse) Descriptor() ([]byte, []int) {
	return file_pb_rifle_proto_rawDescGZIP(), []int{5}
}

func (x *GetRifleResponse) GetRifle() *Rifle {
	if x != nil {
		return x.Rifle
	}
	return nil
}

type Rifle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RifleId            int64   `protobuf:"varint,1,opt,name=rifle_id,json=rifleId,proto3" json:"rifle_id,omitempty"`
	Name               string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SightHeight        float64 `protobuf:"fixed64,3,opt,name=sight_height,json=sightHeight,proto3" json:"sight_height,omitempty"`
	BarrelTwist        float64 `protobuf:"fixed64,4,opt,name=barrel_twist,json=barrelTwist,proto3" json:"barrel_twist,omitempty"`
	TwistDirectionLeft bool    `protobuf:"varint,5,opt,name=twist_direction_left,json=twistDirectionLeft,proto3" json:"twist_direction_left,omitempty"`
	ZeroRange          float64 `protobuf:"fixed64,6,opt,name=zero_range,json=zeroRange,proto3" json:"zero_range,omitempty"`
}

func (x *Rifle) Reset() {
	*x = Rifle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_rifle_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rifle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rifle) ProtoMessage() {}

func (x *Rifle) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rifle_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rifle.ProtoReflect.Descriptor instead.
func (*Rifle) Descriptor() ([]byte, []int) {
	return file_pb_rifle_proto_rawDescGZIP(), []int{6}
}

func (x *Rifle) GetRifleId() int64 {
	if x != nil {
		return x.RifleId
	}
	return 0
}

func (x *Rifle) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rifle) GetSightHeight() float64 {
	if x != nil {
		return x.SightHeight
	}
	return 0
}

func (x *Rifle) GetBarrelTwist() float64 {
	if x != nil {
		return x.BarrelTwist
	}
	return 0
}

func (x *Rifle) GetTwistDirectionLeft() bool {
	if x != nil {
		return x.TwistDirectionLeft
	}
	return false
}

func (x *Rifle) GetZeroRange() float64 {
	if x != nil {
		return x.ZeroRange
	}
	return 0
}

var File_pb_rifle_proto protoreflect.FileDescriptor

var file_pb_rifle_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x62, 0x2f, 0x72, 0x69, 0x66, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x35, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x69,
	0x66, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x05, 0x72, 0x69,
	0x66, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x52,
	0x69, 0x66, 0x6c, 0x65, 0x52, 0x05, 0x72, 0x69, 0x66, 0x6c, 0x65, 0x22, 0x36, 0x0a, 0x13, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x69, 0x66, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x72, 0x69, 0x66, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x69, 0x66, 0x6c, 0x65, 0x52, 0x05, 0x72, 0x69,
	0x66, 0x6c, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x69, 0x66, 0x6c, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x37, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x69, 0x66, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21,
	0x0a, 0x06, 0x72, 0x69, 0x66, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x69, 0x66, 0x6c, 0x65, 0x52, 0x06, 0x72, 0x69, 0x66, 0x6c, 0x65,
	0x73, 0x22, 0x2c, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x69, 0x66, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x69, 0x66, 0x6c, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x69, 0x66, 0x6c, 0x65, 0x49, 0x64, 0x22,
	0x33, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x69, 0x66, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x72, 0x69, 0x66, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x69, 0x66, 0x6c, 0x65, 0x52, 0x05, 0x72,
	0x69, 0x66, 0x6c, 0x65, 0x22, 0xcd, 0x01, 0x0a, 0x05, 0x52, 0x69, 0x66, 0x6c, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x72, 0x69, 0x66, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x72, 0x69, 0x66, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x73, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0b, 0x73, 0x69, 0x67, 0x68, 0x74, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x21, 0x0a, 0x0c, 0x62, 0x61, 0x72, 0x72, 0x65, 0x6c, 0x5f, 0x74, 0x77, 0x69, 0x73, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x62, 0x61, 0x72, 0x72, 0x65, 0x6c, 0x54, 0x77,
	0x69, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x14, 0x74, 0x77, 0x69, 0x73, 0x74, 0x5f, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x12, 0x74, 0x77, 0x69, 0x73, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x4c, 0x65, 0x66, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x7a, 0x65, 0x72, 0x6f, 0x5f, 0x72, 0x61,
	0x6e, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x7a, 0x65, 0x72, 0x6f, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x42, 0x6e, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x62, 0x42, 0x0a,
	0x52, 0x69, 0x66, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x30, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x66, 0x72,
	0x65, 0x61, 0x6b, 0x30, 0x30, 0x33, 0x2f, 0x62, 0x61, 0x6c, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x63,
	0x2d, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x62, 0xa2, 0x02,
	0x03, 0x50, 0x58, 0x58, 0xaa, 0x02, 0x02, 0x50, 0x62, 0xca, 0x02, 0x02, 0x50, 0x62, 0xe2, 0x02,
	0x0e, 0x50, 0x62, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x02, 0x50, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_rifle_proto_rawDescOnce sync.Once
	file_pb_rifle_proto_rawDescData = file_pb_rifle_proto_rawDesc
)

func file_pb_rifle_proto_rawDescGZIP() []byte {
	file_pb_rifle_proto_rawDescOnce.Do(func() {
		file_pb_rifle_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_rifle_proto_rawDescData)
	})
	return file_pb_rifle_proto_rawDescData
}

var file_pb_rifle_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pb_rifle_proto_goTypes = []interface{}{
	(*CreateRifleRequest)(nil),  // 0: pb.CreateRifleRequest
	(*CreateRifleResponse)(nil), // 1: pb.CreateRifleResponse
	(*ListRiflesRequest)(nil),   // 2: pb.ListRiflesRequest
	(*ListRiflesResponse)(nil),  // 3: pb.ListRiflesResponse
	(*GetRifleRequest)(nil),     // 4: pb.GetRifleRequest
	(*GetRifleResponse)(nil),    // 5: pb.GetRifleResponse
	(*Rifle)(nil),               // 6: pb.Rifle
}
var file_pb_rifle_proto_depIdxs = []int32{
	6, // 0: pb.CreateRifleRequest.rifle:type_name -> pb.Rifle
	6, // 1: pb.CreateRifleResponse.rifle:type_name -> pb.Rifle
	6, // 2: pb.ListRiflesResponse.rifles:type_name -> pb.Rifle
	6, // 3: pb.GetRifleResponse.rifle:type_name -> pb.Rifle
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pb_rifle_proto_init() }
func file_pb_rifle_proto_init() {
	if File_pb_rifle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_rifle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRifleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_rifle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRifleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_rifle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRiflesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_rifle_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRiflesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_rifle_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRifleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_rifle_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRifleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_rifle_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rifle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_rifle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_rifle_proto_goTypes,
		DependencyIndexes: file_pb_rifle_proto_depIdxs,
		MessageInfos:      file_pb_rifle_proto_msgTypes,
	}.Build()
	File_pb_rifle_proto = out.File
	file_pb_rifle_proto_rawDesc = nil
	file_pb_rifle_proto_goTypes = nil
	file_pb_rifle_proto_depIdxs = nil
}
