// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: pb/service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BallisticService_CreateLoad_FullMethodName = "/BallisticService/CreateLoad"
)

// BallisticServiceClient is the client API for BallisticService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BallisticServiceClient interface {
	CreateLoad(ctx context.Context, in *CreateLoadRequest, opts ...grpc.CallOption) (*CreateLoadResponse, error)
}

type ballisticServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBallisticServiceClient(cc grpc.ClientConnInterface) BallisticServiceClient {
	return &ballisticServiceClient{cc}
}

func (c *ballisticServiceClient) CreateLoad(ctx context.Context, in *CreateLoadRequest, opts ...grpc.CallOption) (*CreateLoadResponse, error) {
	out := new(CreateLoadResponse)
	err := c.cc.Invoke(ctx, BallisticService_CreateLoad_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BallisticServiceServer is the server API for BallisticService service.
// All implementations must embed UnimplementedBallisticServiceServer
// for forward compatibility
type BallisticServiceServer interface {
	CreateLoad(context.Context, *CreateLoadRequest) (*CreateLoadResponse, error)
	mustEmbedUnimplementedBallisticServiceServer()
}

// UnimplementedBallisticServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBallisticServiceServer struct {
}

func (UnimplementedBallisticServiceServer) CreateLoad(context.Context, *CreateLoadRequest) (*CreateLoadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLoad not implemented")
}
func (UnimplementedBallisticServiceServer) mustEmbedUnimplementedBallisticServiceServer() {}

// UnsafeBallisticServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BallisticServiceServer will
// result in compilation errors.
type UnsafeBallisticServiceServer interface {
	mustEmbedUnimplementedBallisticServiceServer()
}

func RegisterBallisticServiceServer(s grpc.ServiceRegistrar, srv BallisticServiceServer) {
	s.RegisterService(&BallisticService_ServiceDesc, srv)
}

func _BallisticService_CreateLoad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLoadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BallisticServiceServer).CreateLoad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BallisticService_CreateLoad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BallisticServiceServer).CreateLoad(ctx, req.(*CreateLoadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BallisticService_ServiceDesc is the grpc.ServiceDesc for BallisticService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BallisticService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BallisticService",
	HandlerType: (*BallisticServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLoad",
			Handler:    _BallisticService_CreateLoad_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/service.proto",
}
